#!/usr/bin/env bash

set -e

startpath=$(pwd)

cp -vr ./* /etc/nixos
cp -vr .applyignore /etc/nixos/.gitignore

echo

cd /etc/nixos

if [[ ! -d .git ]]; then
	git init
fi

git add .
git config user.name "root"
git config user.email "root@nixos.local"

echo

if [[ -z $1 ]]; then
	nixos-rebuild switch
else
	nixos-rebuild switch --flake "/etc/nixos/#$1"
fi

echo

git add flake.lock

if [[ -z "$(git status --porcelain)" ]]; then
	echo "No changes to commit."
else
	git commit -m "derivation $(date)"
fi

cd $startpath
cp -v /etc/nixos/flake.lock .
