{
  flake.modules.nixos.gui = {
    programs.hyprland = {
      enable = true;
      xwayland.enable = true;
    };
    programs.hyprlock.enable = true;
    security.pam.services.hyprlock = { };
  };

  flake.modules.homeManager.gui =
    {
      config,
      lib,
      pkgs,
      ...
    }:
    let
      paths = {
        kitty = lib.getExe pkgs.kitty;
        rofi = lib.getExe pkgs.rofi;
        hyprshot = lib.getExe pkgs.hyprshot;
        playerctl = lib.getExe pkgs.playerctl;
        brightnessctl = lib.getExe pkgs.brightnessctl;
        hyprlock = lib.getExe pkgs.hyprlock;
        file_manager = lib.getExe pkgs.nautilus;
        hyprmon = lib.getExe pkgs.hyprmon;
        wpctl = "${pkgs.wireplumber}/bin/wpctl";
        hyprctl = "${pkgs.hyprland}/bin/hyprctl";
      };

      toLuaString = s: "\"" + lib.escape [ "\"" "\\" ] s + "\"";
      toLuaTable =
        attrs:
        "{\n"
        + lib.concatStringsSep ",\n" (lib.mapAttrsToList (k: v: "    ${k} = ${toLuaString v}") attrs)
        + "\n}";

      preludeLua = ''
        -- generated by modules/hyprland.nix
        local paths = ${toLuaTable paths}
        local cursor = { name = ${toLuaString config.home.pointerCursor.name}, size = ${toString config.home.pointerCursor.size} }

      '';

      swaync-client = "${pkgs.swaynotificationcenter}/bin/swaync-client";
    in
    {
      # compositor
      wayland.windowManager.hyprland = {
        enable = true;
        systemd.enable = true;
        configType = "lua";
        extraConfig = lib.mkOrder 100 (preludeLua + builtins.readFile ./hyprland.lua);
      };

      services.hyprpolkitagent.enable = true;

      # screen lock + idle.
      services.hypridle = {
        enable = true;
        settings = {
          general = {
            lock_cmd = "pidof hyprlock || ${paths.hyprlock} --immediate-render --no-fade-in --grace 60";
            before_sleep_cmd = "${pkgs.systemd}/bin/loginctl lock-session";
            after_sleep_cmd = "${paths.hyprctl} dispatch dpms on";
          };
          listener = lib.mkDefault [ ];
        };
      };

      programs.hyprlock = {
        enable = true;
        settings = {
          general = {
            hide_cursor = true;
            immediate_render = true;
          };
          background = [ { color = "rgb(000000)"; } ];
          input-field = [
            {
              size = "50%, 50%";
              position = "0, 0";
              monitor = "";

              dots_center = true;
              dots_text_format = "*";
              dots_size = 0.2;
              dots_spacing = 0.2;

              font_color = "rgb(7F7F7F)";
              inner_color = "rgb(000000)";
              outer_color = "rgb(000000)";
              placeholder_text = "";
              rounding = 0;
              font_family = builtins.head config.fonts.fontconfig.defaultFonts.monospace;

              fade_on_empty = true;
              fade_timeout = 5 * 60 * 1000;

              numlock_color = "rgb(000000)";
              capslock_color = "rgb(7F007F)";
              bothlock_color = "rgb(7F007F)";

              fail_color = "rgb(7F0000)";
              fail_text = "";

              check_color = "rgb(007F7F)";

              halign = "center";
              valign = "center";
            }
          ];
        };
      };

      # rofi launcher
      programs.rofi = {
        enable = true;
        theme = "gruvbox-dark-soft";
      };

      # xdg portals
      home.packages = with pkgs; [
        xdg-desktop-portal
        xdg-desktop-portal-hyprland
        xdg-desktop-portal-gnome
        brightnessctl
        playerctl
        power-profiles-daemon
      ];

      xdg.portal = {
        enable = true;
        config.common.default = [
          "hyprland"
          "gtk"
        ];
      };

      # waybar
      programs.waybar = {
        enable = true;

        style =
          builtins.replaceStrings
            [ "\${font-family}" ]
            [
              "${builtins.concatStringsSep ", " (
                map (s: "\"${s}\"") config.fonts.fontconfig.defaultFonts.monospace
              )}"
            ]
            (builtins.readFile ./waybar.css);

        settings.mainBar = {
          position = "top";
          layer = "top";
          height = 16;
          spacing = 0;
          margin-top = 0;
          margin-right = 0;
          margin-left = 0;

          modules-left = [
            "hyprland/workspaces"
            "hyprland/submap"
          ];
          modules-center = [ "clock" ];
          modules-right = [
            "pulseaudio"
            "backlight"
            "battery"
          ];

          "hyprland/workspaces".separate-outputs = true;
          "hyprland/submap" = {
            format = "{}";
            tooltip = false;
          };

          tray = {
            icon-size = 12;
            spacing = 7;
          };

          backlight = {
            format = " 󰃠 {percent}%";
            on-scroll-down = "${paths.brightnessctl} set 5%+";
            on-scroll-up = "${paths.brightnessctl} set 5%-";
            smooth-scrolling-threshold = 1;
            tooltip = false;
            tooltip-format = "Brightness: {percent}%";
          };

          pulseaudio = {
            scroll-step = 1;
            format = "{icon} {volume}%";
            format-muted = "󰝟 {volume}%";
            format-bluetooth = "󰂰 {volume}%";
            format-bluetooth-muted = "󰂲 {volume}%";
            format-source = "󰍬 {volume}%";
            format-source-muted = "󰍭";
            format-icons.default = [
              "󰕿"
              "󰖀"
              "󰕾"
            ];
            on-click = "${paths.wpctl} set-mute @DEFAULT_AUDIO_SINK@ toggle";
            on-scroll-down = "${paths.wpctl} set-volume -l 1 @DEFAULT_AUDIO_SINK@ 1%+";
            on-scroll-up = "${paths.wpctl} set-volume -l 1 @DEFAULT_AUDIO_SINK@ 1%-";
            tooltip = false;
            tooltip-format = "{desc} - {volume}%";
            max-volume = 100;
          };

          battery = {
            interval = 10;
            states = {
              good = 99;
              warning = 30;
              critical = 20;
            };
            format-icons = [
              "󰂎"
              "󰁺"
              "󰁻"
              "󰁽"
              "󰁾"
              "󰁿"
              "󰂀"
              "󰂁"
              "󰂂"
              "󰁹"
            ];
            format = " {icon} {capacity}%";
            format-critical = " {icon} {capacity}%";
            format-warning = " {icon} {capacity}%";
            format-full = " {icon} {capacity}%";
            format-charging = " 󰂅 {capacity}%";
            format-charging-warning = " 󰢝 {capacity}%";
            format-charging-critical = " 󰢜 {capacity}%";
            format-plugged = " 󰂅 {capacity}%";
            tooltip = true;
            tooltip-format = " 󱧥 {time}";
          };

          clock = {
            format = "{:%H:%M}";
            tooltip = true;
            tooltip-format = "{:%Y-%m-%d}";
            interval = 1;
          };

          mpris = {
            format = "{title} - {artist}";
            status-icons.paused = "⏸";
            tooltip = false;
          };

          "power-profiles-daemon" = {
            format = "{icon}";
            tooltip-format = "{profile}";
            tooltip = true;
            format-icons = {
              default = " 󰥔 ";
              performance = "  ";
              balanced = "  ";
              power-saver = "  ";
            };
          };

          "custom/notification" = {
            tooltip = false;
            format = "{icon}";
            format-icons = {
              notification = "<span foreground='red'><sup></sup></span>";
              none = "";
              dnd-notification = "<span foreground='red'><sup></sup></span>";
              dnd-none = "";
              inhibited-notification = "<span foreground='red'><sup></sup></span>";
              inhibited-none = "";
              dnd-inhibited-notification = "<span foreground='red'><sup></sup></span>";
              dnd-inhibited-none = "";
            };
            return-type = "json";
            exec-if = "which ${swaync-client}";
            exec = "${swaync-client} -swb";
            on-click = "${swaync-client} -t -sw";
            on-click-right = "${swaync-client} -d -sw";
            escape = true;
          };

          "custom/submapKeybinds" = {
            tooltip = false;
            format = "bindings";
          };
        };
      };

      systemd.user.services.waybar = {
        Unit = {
          Description = "Waybar";
          PartOf = [ "hyprland-session.target" ];
          After = [ "hyprland-session.target" ];
        };
        Service = {
          ExecStart = "${pkgs.waybar}/bin/waybar";
          Restart = "on-failure";
          RestartSec = 1;
        };
        Install.WantedBy = [ "hyprland-session.target" ];
      };
    };
}
